# Site settings
title: 爱夏
header-img: "img/autumn2.jpg"
tagline: "爱夏"  
description: "还有二十来岁遇见的她。"  
baseurl: ""
url: "http://azeril.me"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "aixia"
  email: 920534583@qq.com
  bio: "人生苦短 我用Python"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.ico

douban_username: 
twitter_username:  
github_username: aixiamomo  
facebook_username:   
weibo_username: 爱夏手作-石榴石  
zhihu_username: 爱夏  

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

gems: 
- jekyll-gallery-generator
- jekyll-paginate
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "aixia"
      header-img: "img/fantasy.jpg" # We don't want posts without a header image, that whould mean white on white


# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : 爱夏
  disqus :
      short_name : 爱夏

# Analytics and webmaster tools stuff goes here
google_analytics: UA-66863061-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation